#+TITLE: Teoria Ergodica e Dinamica Topologica
#+AUTHOR: Dario Balboni
#+DATE:
#+LANGUAGE: it
#+OPTIONS: H:4 toc:nil
#+LaTeX_class_options: [a4paper, 11pt]
#+LaTeX_header: \hypersetup{colorlinks=true,linkcolor=black,citecolor=black,filecolor=black,urlcolor=black}
#+LaTeX_header: \usepackage[AUTO]{babel}
#+LaTeX_header: \usepackage[left=20mm,textwidth=167mm,headsep=8mm,footskip=20pt,top=2.5cm,bottom=2.5cm]{geometry}
#+LaTeX_header: \usepackage{diagrams}
#+LaTeX_header: \input{latex-abbreviations}

\setlength{\parindent}{0em}
\setlength{\parskip}{1em}
\setlist{nosep}
\linespread{1.2}
\titlespacing\section{0pt}{0pt}{0pt}
\titlespacing\subsection{0pt}{0pt}{0pt}
\titlespacing\subsubsection{0pt}{0pt}{0pt}

* Definizioni
  - (*Deterministic Dynamical system*, from an article of Smale, '67)  A dynsys is the datum of:
    * $G$ a semi-group (which gives the notion of time, e.g. $\bbN, \bbZ, \bbR$)
    * $X$ is a phase space, that can be:
      - A locally compact metric space $\rar$ topological dynamics
      - A Measure Space $(X, \cA, \mu)$ s.t. $\mu(X) = 1$ (compactness equation)

    The dynsys is specified by an action of $G$ on $X$: $\Phi: G \times X \rar X$ defined by $\Phi(g, x) = \phi_g (x)$ satisfying:
    1. $\phi_e(x) = x$
    2. $\phi_{g + h}(x) = \phi_g \circ \phi_h (x)$
    3. $\forall g : \phi_g \in \End(X)$

    Moreover:
    * If $X$ is a metric space, then $\phi_g$ is assumed to be continuous
    * If $X$ is a measure space, we ask that $\forall A \in \cA : \mu(\phi_g^{-1}(A)) = \mu(A)$
  
    *Remark*: Every ODE or PDE of evolution time with global existance is a dynamical system.

    *Remark*: Every continuous dynsys becomes a discrete dynsys ($G = \bbZ$) by stroboscopic observation.
    i.e. Fix $\tau > 0$ and consider $(\phi_{n\tau})_{n \in \bbZ}$. The choice of $\tau$, concerning the applications, is the busillis.
  - (*Conjugate dynsys*) Two $G$-actions on $X$: $(\phi, \psi)$ are conjugated iff there $\exists \xi \in \Aut(X)$ s.t. the following diagram commutes
    \begin{diagram}
    X & \rTo^{\psi_g} & X \\
    \dTo^{\xi} & & \dTo_{\xi} \\
    X & \rTo^{\phi_g} & X \\
    \end{diagram}
    i.e. the two systems have the same orbit under a fixed change of coordinate.
    It is a natural notion for discdynsys but it is too much for contdynsys, because I'm also asking that the orbits have the same speed.
  - (*Topologically Conjugate Homeo*)
    Let $f, g: X \rar X$ be two homeomorphisms, and $X$ a compact metric space.
   
    We say that $f$ and $g$ are *topologically conjugate* if there $\exists h: X \rar X$ homeomorphism such that $f \circ h = h \circ g$.
    In such case of course we also have $f^n \circ h = h \circ g^n$.
  - (*Structurally stable systems*) $X$ $\cC^r$ compact manifold with $r \ge 0$.
    Denote by $\cG^r$ the $\cC^r$ dynamical discrete system on $X$: $\cG^r = \Diff^r(X)$, which is a topological space with the local distance given by the sup of the difference of the sum of the derivatives in a ball.
    
    Theorem: $\cG^r$ is a banach manifold.
  - (*Structurally stable dynamics*) The set $SS(X)$ of structurally stable dynamical systems is $\lrg{ f \in \cG \mid \exists W \text{ open neigh. of } f s.t. \forall g \in W \implies g \sim_\text{top} f }$.
    The complement of the SS points of $\cG$ is called the bifurcation set (which is closed).
  - (*Wandering Point*) $x \in X$ is wandering iff $\exists U$ neigh. of $x$ s.t. $\lrt{\cup_{n \neq 0\in \bbZ} f^n(U)} \cap U = \empty$.

    $\Omega(f) = \lrg{x \in X \mid x \text{ not wandering }}$.

    Definition of $\alpha$ and $\omega$ limits of $x$:
    - $\alpha(x)$ is the set of all acculumations points of the orbit of x _in the past_
    - $\omega(x)$ is the set of all accumulations points of the orbit of x _in the future_
      
      that is $y \in \omega(x)$ iff $\exists n_k \rar \infty$ s.t. $x_{n_k} \rar y$.

    Two alternative definitions are:
    $$ 
       \alpha(x) = \cap_{n < 0} \bar{\cup_{m \le n} f^m(x)} \hskip 1.5em
       \omega(x) = \cap_{n > 0} \bar{\cup_{m \ge n} f^m(x)}
    $$
  - (*Recurrent points*) A point $x$ is (positively / negatively) recurrent iff $x \in \omega(x)$ / $x \in \alpha(x)$.
    And it's said to be recurrent if $x \in \alpha(x) \cap \omega(x)$ \sse x \in \Omega(f)$.

    We define the reccurent point of $A$ by $A_\text{rec} = \lrg{x \in A \mid f^n(x) \in A \text{ for } \infty \text{ many } n \in \bbN}$.
  - (*Devaney chaos*) A system $(X, d, f)$ is chaotic /à la Devaney/ iff it is toptrans and the set of periodic points $\Per(f)$ is dense.
  - (*SDOIC - Sensitive Dependence on Initial Conditions*) $(X, d, f)$ is SDOIC at a point $x_0 \in X$ iff there $\exists \varepsilon > 0$ $\exists U$ nghb. of $x_0$ st. $\forall y_0 \in U$ there $\exists n \ge 0$ : $d(f^n(x_0), f^n(y_0)) > \varepsilon$.
    
    *Remarks*: 
    - Isometries are never SDOIC
    - Uniformly expanding maps must be SDOIC
  - (*Lyapounov Stability*) $(X, d, f)$ is lyapounov stable at $x_0$ iff $\forall \varepsilon > 0$ there $\exists U$ nhbg of $x_0$ s.t. $\forall y_0 \in U$ $\forall n \ge 0$ : $d(f^n(x_0), f^n(y_0)) < \varepsilon$.
  - (*Ergodicity*) $(X, \cA, \mu, f)$ a meas discdynsys and $\mu(f^{-1}(A)) = \mu(A) \quad \forall A \in \cA$.
    
    /Idea/: We want to interpret $\mu$ as a probability "naturally generated from the dynamics", i.e. what is its relation to the statistics of the orbits?
    
    We are asking if it holds the law of large numbers:
    $$\bbE[\phi] \stackrel{?}{=} \lim_{T \rar \infty} \frac{1}{T} \sum_{j = 0}^{T - 1} \phi \circ f^j(x)$$
    If the equality holds we call such system *ergodic*. Note that $\phi \circ f^j(x) = \phi(x_j)$.
    
    1. Is there a statistics associated to orbits of $f$? (See Birkoff theorem)
    2. Are the empirical frequencies (computed by means of the orbit) converging to the apriori probability of $\mu$? (Content of Ergodicity)
       
    ------
    Let $A \in \cA, x_0 \in X, T > 0$. We define:
    - "number of visits of the orbit of length $T$ of $x_0$ to $A$": $\cN(A, x_0, T) = \sum_{j = 0}^{T - 1} \chi_A (f^j(x_0))$.
    - "average frequency of visits of ...": $\nu(A, x_0, T) = \cN(A, x_0, T) \cdot \frac1T$.
    - "upper and lower frequencies of visits to the orbit of $x_0$ to $A$": $\bar{\nu}(A, x_0) = \limsup_{T \rar \infty} \nu(A, x_0, T)$ and $\underline{\nu}{A, x_0) = \liminf_{T \rar \infty} \nu(A, x_0, T)$.
      
    If $\underline{\nu}(A, x_0) = \bar\nu(A, x_0)$ we call it the frequency of visits and denote it by $\nu(A, x_0)$.

    *Birkoff sum*: Given an observable $\phi: X \rar \bbR$ we define the "Birkoff sum" of $\phi$ along a segment of orbit of $x_0$ of length $T$ by $(\cS_T \phi)(x_0) = \sum_{j=0}^{T-1} \phi(x_j)$.
    
    The "time average of $\phi$ ..." is $\frac1T (\cS_T \phi)(x_0)$ and if $\lim_{T \rar \infty} \frac1T (\cS_T \phi)(x_0)$ exists then we call it $\lra{\phi}(x_0)$ and we have $\lra\phi \circ f = \lra\phi$.
    - (*Birkoff theorem*) Let $(X, \cA, \mu, f)$ be a measurable dynsys:
      1. $\forall A \in \cA$ and $\mu$-a.e. $x_0 \in X$ we have $\nu(A, x_0)$ exists
      2. $\forall \phi \in \cL^1$ and $\mu$-a.e. $x_0 \in X$ the time average $\lra\phi$ exists

    - (*Ergodicity*) A MDS is *ergodic* iff $\forall A \in \cA$, $\mu$-a.e. $x_0 \in X$ : $\nu(A, x_0) = \mu(A)$.

      TFAE:
      1. The dynsys is *ergodic* and *topologically transitive*
      2. (*Metrical indecomposability*) $\forall A \in \cA$, $A$ is $f$-invariant $\implies$ $\mu(A) = 0$ or $\mu(A) = 1$
      3. $\forall \phi$ observable, $\phi$ is a first integral, i.e. $\exists c \in \bbR$ s.t. $\phi = c$ $\mu$-a.e.
      4. $\forall \phi \in \cL^1$ observable and $\mu$-a.e. $x_0 \in X$ we have $\lra\phi = \bbE_\mu[\phi] = \lim_{T \rar \infty} \frac1T \sum_{j = 0}^{T - 1} \phi \circ f^j == \int_X \phi \de\mu$.
      5. $\forall A, B \in \cA$: $\lim_{n \rar \infty} \frac1n \sum_{j = 0}^{n - 1} \mu(f^{-j}(A) \cap B) = \mu(A) \mu(B)$
   - (*Strongly mixing*) We say a MDS is strongly mixing iff $\forall A, B \in \cA$ we have $\lim_{n \rar \infty} \mu(f^{-n}(A) \cap B) = \mu(A) \mu(B)$.
     
     This *implies ergodicity*. The converse does not hold.
   - (*Lyapounov exponent for map of intervals preserving $\mu$*): $\lambda = \int_I \ln\abs{f'(x)} \de\mu(x)$, that exists because $\frac1n \sum_{j = 0}^{n - 1} \ln\abs{f'(x_j)}$ converges $\mu$-a.e.
   - (*Hahn decomposition of a measure*) Let $(X, \cA, \mu)$ and $\mu$ a signed measure.
     Then there $\exists P, N \in \cA$ s.t.:
     1. $P \cap N = \emptyset$ and $P \cup N = X$
     2. $\forall E \subseteq P$ and $E \in \cA$ we have $\mu(E) \ge 0$
     3. $\forall E \subseteq N$ and $E \in \cA$ we have $\mu(E) \le 0$

     Moreover, $P$ and $N$ are uniquely determined, except for a set of null measure.
     We will denote $\mu^+(E) = \mu(E \cap P)$ and $\mu^-(E) = \mu(E \cap N)$.
   - (*Extreme points of a convex subset of tvs*) Let $S \subseteq X$ and $S$ convex.
     Then $x_0 \in S$ is an extremal point of $S$ if $x_0 \notin$ any open segment joining two points of $S$.
   
     *Krein-Milman Theorem*: Let $X$ be a lctvs and $S \subseteq X$ a convex.
     Then $S$ is the /closed convex hull/ of its extremal points.
   - (*Unique ergodicity*) iff $\cM_f(X) = \lrg\mu$.
   - (*Support of a measure*) $\supp \mu = \bar\lrg{x \in X \mid \forall U \subseteq X \text{ open }, x \in U \implies \mu(U) > 0}$
   - (*1-coboundaries*) Let $X4 be a compact metric space and $f: X \rar X$ an homeomorphism.
     A continuous observable $\phi \in \cC^0(X, \bbR)$ is a 1-coboundary iff $\exists \psi \in \cC(X, \bbR)$ s.t.
     $$\phi = \psi\circ f - \psi = \de_f \psi$$

     We can then show that $\cM_f^\text{sign}(X) \simeq \de_f\cC(X, \bbR)^\top = \frac{\cC(X, \bbR)}{\bar{\de_f \cC(X, \bbR)}}$.

     From that follows that *corollary*: $f$ is uniquely ergodic iff $\bar{\de_f \cC(X, \bbR)}$ has codimension $1$ in $\cC(X, \bbR)$.

     *Exercise*: If $\phi$ is a coboundary then $\frac1n \sum_{j = 0}^{n - 1} \phi \circ f^j \stackrel{\rar}{\rar} 0$.
   - (*IET - Interval Exchange Transformations*) Let $\cA$ be an alphabet of cardinality $\abs\cA = d$ and $T = (\pi, \lambda)$ where $\pi = (\pi_0, \pi_1)$ a pair of bijections from $\cA$ to $\lrg{1, \ldots, d}$.
     $\lambda$ is a vector $\lrt{\lambda_a}_{a \in \cA} \in \bbR^{\abs\cA}_+$. Spesso chiederemo inoltre $\sum_\alpha \lambda_\alpha = 1$.

     Consideriamo $I = \sqcup_{\alpha \in \cA} I_\alpha$ con $\abs{I_\alpha} = \lambda_\alpha$.

     *Admissible permutation*: $\pi$ is admissible (not two separated pieces) if $\forall 1 \le k < d$ we have $\pi_0^{-1}(\lrg{1, \ldots, k}) \neq \pi_1^{-1}(\lrg{1, \ldots, k])$.
     
     *Connection*: A connection for the IET $T = (\pi, \lambda)$ is $(\alpha, \beta, m)$ with $\alpha, \beta \in \cA$, $m \in \bbN$ and $\pi_0(\beta) > 1$ s.t. $T^m(\partial I_\alpha) = \partial(I_\beta)$.
     $T$ is said to satisfy the *Keane property* if it has no connection.

     *Keane theorem*:
     1. If $T$ has no connections $\implies$ $T$ is minimal.
     2. $\lambda_\alpha$ linearly independent on $\bbQ$ $\implies$ $T$ has no connections.

     The natural measure on the space of IET is the counting measure on $\pi$, and the Lebesgue measure on $\lambda_i$, then almost certainly the $\lambda_\alpha$ are $\bbQ$-independent.

     Keane produces an example of $T$ with no connections which is not uniquely ergodic.
     Few years later it was proved that almost every IET is uniquely ergodic.
  - (*Operatore Koopman*) Given $(X, \cA, \mu, f)$ where $f$ preserves $\mu$, $\phi \in \cL^2$ we define $U_f \phi = \phi \circ f$.
    It is a unitary operator on $\cL^2$ and we will study its spectrum.
  - (*Shannon entropy*) Let $\phi$ be an event that has only finitely possible outcomes $A_1, \ldots, A_n$ with probabilities $p_1, \ldots, p_n$ that sum to one.
    
    We consider $H^n: \Delta^n \rar [0, +\infty)$ with $\Delta^n$ the symplex of dimension $n-1$ and we ask the following properties to hold for $H^n$:
    1. Completely symmetric: $H^n(\ldots, p_i, \ldots, p_j, \ldots) = H^n(\ldots, p_j, \ldots, p_i, \ldots)$
    2. $H^n(1, 0, \ldots, 0) = 0$ (should measure the uncertainty)
    3. $H^n(0, p_2, \ldots, p_n) = H^{n-1}(p_2, \ldots, p_n)$ (reducibility in case of null outcome)
    4. $H^n(p_1, \ldots, p_n) \le H^n(\frac1n, \ldots, \frac1n)$ (max uncertainty with equal probability outcomes)
    5. If $A$ and $B$ are partitions, with $A$ finer than $B$, then $H(A) = H(B) + H(A\mid B)$

       That is, if $A$ is $\pi_{ij}$ and $B$ is $p_i$ then $\abs{A} = nl$ and $\abs{B} = n$ with $p_i = \sum_j \pi_{ij}$ then we have
       $$H^{np}(\pi_{11}, \ldots, \pi_{1l}, \pi_{21}, \ldots) = H^n(p_1, \ldots, p_n) + \sum_i p_i H^p(\frac{\pi_{i1}]{p_i}, \ldots, \frac{\pi_{ip}}{p_i})$$
    6. $H$ must be continuous

    If $H^n$ satisfies the conditions above, then it satisfies:
    $\exists c > 0$ s.t. $H^n(p_1, \ldots, p_n) = - c \sum_i p_i \log p_i$.
  - (*Kolmogorov-Sinai entropy*) 
    Let $(X, \cA, \mu, f)$ be ergodic, and take two partitions $\cP = \lrg{A_1, \ldots, A_n}$ and $\cQ = \lrg{B_1, \ldots, B_l}$ s.t. $X = \sqcup_i A_i = \sqcup_i B_i$ modulus trascurable sets and set $\cP \vee \cQ = \lrg{A_i \cap B_j}$.
    
    Now we can define $\vee_{i=0}^{T-1} f^i \cP = \cP \vee f^{-1} \cP \vee \ldots \vee f^{-(T-1)} \cP$, which has at most $n^T$ sets, and denote $n_k = \card (\vee_{i=0}^{k-1} f^i \cP)$.
    We can now define $a(k) = \frac1k H^{n_k}(\vee_{i=0}^{T-1} f^i \cP)$ where the $p_i = \mu(A_i)$ and define $h(f, \cP) = \lim_{T \rar \infty} a(T)$, which is well defined since $H^{n_T}$ is subadditive in $T$.

    Finally the *KS-entropy* is defined as $h_{KS}(f, \mu) = \sup \lrg{h(f, \cP) \mid \cP \text{ is a finite partition wrt } \mu \text{ of } X}$.

    /Properties/:
    1. $h_{KS}$ is isomorphism-invariant (that preserve null sets)
    2. (*Sinai Theorem*): If $\cP$ is generating (i.e. $f^{-1}(\cP)$ generates $\cA$ as a $\sigma$-algebra) then $h_{KS}(f, \mu) = h_{KS}(f, \cP)$.
  - (*Topological entropy*) Let $(X, d, f)$ with $(X, d)$ compact metric space and $f$ an homeomorphism of $X$.

    $\forall n \ge 0$ we define $d_n(x, y) = \max \lrg{d(f^i(x), f^i(y)) \mid i \in \lrg{0, \ldots, n-1}}$, which is a metric equivalent to $d$.

    /Definitions/:
    * We say that $S \subseteq X$ is $(n, \varepsilon)$ /spanning/ if $\forall x \in X$ : $\exists y \in S$ s.t. $d_n(x, y) < \varepsilon$.
    * $r(n, \varepsilon) = \min \lrg{\abs{S} \mid S \text{ is } (n, \varepsilon) \text{ spanning}} < \infty$.
    * *Topological entropy*: $h_{TOP}(f) = \lim_{\varepsilon \rar 0} \limsup_{n \rar \infty} \frac1n \log(r(n, \varepsilon))$.
      It exists because the limsup is decreasing in $\varepsilon$.

    /Properties/:
    1. $f$ isometry $\implies h_{TOP}(f) = 0$
    2. $f$ is homeomorphism $\implies h_{TOP}(f) = h_{TOP}(f^{-1})$.
    3. $h_{TOP}(f^m} = \abs{m} h_{TOP}(f)$.
    4. Topological entropy does not change if $d$ is replaced by $d'$, an equivalent metric.
       With the same proof, we get that a surjective map gets up a inequality between entropies.

    Moreover, we have the *entropy inequality*: $h_{KS}(\mu) \le h_{TOP}(f)$.
  - (*Equivalent definition of top. entropy*) $A \subseteq X$ is $(n, \varepsilon)$ separated if $\forall x, y \in A$, $x \neq y$ and $d_n(x, y) \ge \varepsilon$ we have $s(n, \varepsilon) = \max \lrg{ \card A \mid A \text{ is } \varepsilon \text{ separated }}$.
    Then $h_{TOP}(f) = \lim_{\varepsilon \rar 0} \limsup_{n \rar \infty} \frac1n \log(s(n, \varepsilon))$.

    This roughly corresponds to how many different orbits (truncated to the time $n$) you can distinguish if you miopia is $\varepsilon$.
  - (*Another definition of top. entropy*) Given $\alpha, \beta$ open coverings, we call $\alpha \vee \beta := \lrg{A \cap B \mid A \in \alpha, B \in \beta}$ and let $N(\alpha)$ be the minimal cardinality of a subcover (which is $< \infty$ because $X$ is compact).
    We remark that $N(\alpha \vee \beta) \le N(\alpha) N(\beta)$ and that $N(f^{-1}(\alpha)) \le N(\alpha)$.

    We then set $a(n) = \ln N(\vee_{i=0}^{n-1} f^i(\alpha))$ and there exists $\exists \lim_{n \rar \infty} \frac1n \ln\lrq{N(\vee_{i=0}^{n-1} f^i(\alpha))} = h_{TOP}(f, \alpha)$ and $h_{TOP}(f) = \sup_\alpha h_{TOP}(f, \alpha)$.
  - (*Haussdorf space*) Given a complete metric space $(X, d)$ one can define $\cH(X) = \lrg{\text{compact non-empty subsets of } X}$, that is a complete metric space with the metric $h(A, B) = \max\lrg{d(A, B), d(B, A)}$, where $d(A, B) = \max\lrg{d(x, B) \mid x \in A}$.
* Properties of maps
  - (*Topological transitivity*) A dynsys is *topologically transitive* iff $\exists x \in X$ s.t. $\bar{\cO_f(x)} = X$.

    Moreover TFAE:
    1. $f$ is topologically transitive
    2. $U \subseteq X$ open and $f$-invariant (i.e. $U = f(U) = f^{-1}(U)) $\implies U = \emptyset$ or $\bar{U} = X$.
    3. If $U$ and $V$ are open and non-empty then there $\exists n \in \bbN$ s.t. $f^n(U) \cap V \neq \emptyset$
    4. $\lrg{x \in X \mid \bar{\cO_f(x)} = X}$ is a dense $G_\delta$.
  - (*Genericity*) The word "generic" in topological dynamic means that the behaviour happens in a dense $G_\delta$.
  - (*Minimality*) A dynsys is *minimal* iff $\forall x \in X$ : $\bar{\cO_f(x)} = X$.
* Categories
  - (*Suspension*) Given a discdynsys on $X$ represented by the map $f: X \rar X$ we can obtain a contdynsys on $Y$ that is "naturally associated" with the initial one.
    We take $Y = X \times \frac{[0, 1]}{(x, 1) \sim (f(x), 0)}$ and the action is $\frac{\partial}{\partial s}$, i.e. a traslation on the second coordinate. 

    If $X$ is a variety and $f \in \Diff(X)$, then $Y$ is regular.
  - (*Suspension under a roof*) /return time/
    ... and if there is a section s.t. the return time is constant we have a cohomological equation.
  - (*Poincaré section*) It is in a certain sense, the inverse operation of suspension:
  
    We look at an hypersurface $\Sigma$, trasversal to the field of $Y$, and define the map "first comeback on $\Sigma$".
    Note that taking $\Sigma = X$ in the suspension we get to the original discdynsys.
  - (*Factors of maps*) Suppose we have the following diagram:
    \begin{diagram}
    Y & \rTo^{g} & Y \\
    \dTo^{\pi} & & \dTo_{\pi} \\
    X & \rTo^{f} & X \\
    \end{diagram}
    then we say that *f is a factor of g* and that *g extends f*.
  - (*Observables*) An observable is just a function $\phi: X \rar \bbC$ in the same "category" of your phase space X.
    
    Precisely, for topdyn we ask that $\phi \in \cC^0(X, \bbC)$ and for measdyn we ask that $\phi: X \rar \bbC$ be measurable or $\cL^1(X, \cA, \mu)$

    *First integral*: is an observable which is constant along orbits and globally non-constant
  - (*Skew-product*) Let $(X, \cA, \mu, f)$ be a measure preserving transformation and $\phi: X \rar G$ a function.
    Moreover, if $G$ is a locally compact topological group and $G$ acts on $(Y, \cB, \nu)$ in a measure preserving way, then we can define:
    $$S_\phi: X \times Y \rar X \times Y \hskip 1.5em (x, y) \mapsto (f(x), \phi(x) y)$$
    This is a dynsys that extends the original one $(X, \cA, \mu, f)$.
  - (*Transfer operator*) Let $T: I \rar I$ be a non-singular continuous map (i.e., $\mu(A) = 0 \implies \mu(T(A)) = 0$).
    We define the transfer operator as $P_T: \cL^1 \rar \cL^1$ s.t. $\int_A P_T f\de m = \int_{T^{-1}A} f \de m$ for every $A$ measurable.

    /Properties/:
    1. $P_T$ is linear
    2. $P_T$ is positive (i.e. $f \ge 0 \implies P_T f \ge 0$)
    3. Normalization preserving: $\int_I P_T f \de\mu = \int_I f \de m$
    4. is a contraction wrt. $\cL^1$: $\norm{P_T f^+}_1 \le \norm{f}_1$

    *Theorem*: Transfer fix-point define $T$-invariant measures: $P_T f^* = f^*$ and $T$ non-singular iff $\mu(A) = \int_A f^* \de m$ is $T$-invariant
    
    *Theorem*: $T$ non singular, $\mu$ invariant. Then $T$ is ergodic iff $\frac1n \sum_{n = 1}^\infty P_T^n f \rhu^{\cL^1} \mathbb{1}$ for every $f \neq 0$.
* Examples of dynsys
  - (*Irrational rotations of the torus*) $R_\alpha: \bbT^1 \rar \bbT^1 \simeq \bbR/\bbZ$ defined by $R_\alpha(x) = x + \alpha$ for $\alpha \in \bbR \setminus \bbQ$ is *minimal*.
    
    Let now $X = \bbT^n = \bbR^n / \bbZ^n$ for $n \ge 2$ and $R_\alpha: X \rar X$ with $x \mapsto x + \alpha$ where
    $\alpha \in \bbR^n$ must satisfy $k \cdot \alpha + p \neq 0$ $\quad \forall k \in \bbZ^n \setminus \lrg{0}, p \in \bbZ$.
    This is the right condition instead of irrationality in the multidimensional case to be minimal.

    /Properties/: Irrational rotations are *ergodic*.
    *Suspension*: The suspension of the rotation $R_\alpha$ on the unit circle is a linear flow on the torus given by $\dot{x_1} = \omega_1$ and $\dot{x_2} = \omega_2$ where $\alpha = \frac{\omega_1}{\omega_2}$.
  - (*Doubling map. $x \mapsto 2x (\mod 1)$*) is *topologically transitive* but *not minimal*, because zero is a fix point.
    If we write the numbers in binary expansion this system is just the shift of the digit string $\lrg{0, 2}^\bbN$.
    
    Where the shift $\sigma: \lrg{0,1}^\bbN \rar \lrg{0,1}^\bbN$ is defined as: let $s = (s_j)_{j \in \bbN}$ where $s_j \in \lrg{0,1}$ is an element.
    Then the left shift is $(\sigma(s))_j = s_{j+1}$ and the distance between two points is defined as $d(s, t) = 2^{- \min_j \lrg{ s_j \neq t_j }}$.

    A dense point is the concatenation of all possible prefixes: $s = 0 \, 1 \, 00 \, 01 \, 10 \, 11 \, 000 \, \ldots$.
    It is dense because if we want to get near $x_1$ we can search the first digits of the expansion of $x_1$ and then iterate until they are the first digits of $f^n(x_0)$.

    /Properties/: The doubling map is *ergodic*.
  - (*Tent map*) Defined by
    $$F(x) = \left\{ \begin{array}{lr} 2x & x \in [0, \frac{1}{2}] \\ 2 - 2x & x \in [\frac{1}{2}, 1] \\ \end{array} \right.$$
    The lebesgue measure is $F$-invariant.

    /Properties/: It is *ergodic*, *mixing* and *positively entropic*.
  - (*Ulam-Von Neumann map*) Defined by $x \mapsto 4 x (1-x)$. An invariant measure for it is $\de\mu(x) = \frac{\de x}{\pi \sqrt{x (1-x)}}$.

    Conjugated to the Tent Map by a change of variables: $y = \sin^2 \lrt{\frac{\pi x}{2}}$.
  
    In general the family of $x \mapsto \lambda x (1-x)$ where $x \in [0, 1], \lambda \in [0, 4]$ is called the logistic family.
    For low values of $\lambda$ we have an attractive fix point at the origin.
    For high values of lambda the system exibits a chaotic behaviour.
  - (*Cauchy distribution*) $f: \bbR \rar \bbR$ defined by $f(x) = \frac12 \lrt{x - \frac1x}$.
    It preserves $\de\mu(x) = \frac{\de x}{\pi (1 + x^2)}$, it is a distribution that has no moments.
  - (*Hyperbolic automorphisms of the torus are ergodic*) An automorphisms $A$ is hyberbolic when its spectrum $\sigma(A)$ is disjoint from the unit circle iff $\abs{\Tr(A)} > 2$.
    Let $A = \matr{a}{b}{c}{d}$ and let $f_A: \bbT^2 \rar \bbT^2$ induced by $A$ as $f_A \vect{x_1}{x_2} = \vect{a x_1 + b x_2}{c x_1 + d x_2}$.
    Let $\phi: \bbT^2 \rar \bbC$ and from $\phi \circ f_A = \phi$ we get that if $\phi \in \cL^2$ we have $\hat\phi (k) = \hat\phi(\lrt{A^\dagger}^{-1} k) \quad \forall k \in \bbZ^2$
  - (*Hamiltonian ODE*) $H: \bbR^{2n} \rar \bbR$ the map $H(\rab p, \rab q)$ and consider the system given by
    $$\system{\dot p_i = -\frac{\partial H}{\partial q_i} \\ \dot q_i = \frac{\partial H}{\partial p_i}}$$
    
    In Hamiltonian system one wants to preserve the special form of the equation with transformations.

    *CCI - Completely Canonically Integrable systems*: A system is CCI iff there $\exists$ canonical variables ACTION ($J \in B_1 \subseteq \bbR^n$) and ANGLE ($\chi \in \bbT^n$) such that the new Hamiltonian only depends on the actions.
    For a CCI we have that all $J$ are first integrals and $\chi_k(t) = \omega_k(t) + \chi_k(0)$ where $\omega_k(t) = \partial{H}{j_k}(j)$.

    In dimension $n = 1$ all Hamiltonian systems are CCI.

    In dimension $n = 2$ the value of the Hamiltonian is preserved, and we can foliate the space by its "energy".
  - (*Farey map*) $$f(x) = \partdef{\frac1{x-1} & x > \frac12 \\ \frac{x}{1-x} & x < \frac12}$$
    It is ergodic wrt $\de\mu(x) = \frac{\de x}{x}$.
  - (*Bernoulli Schemes*) Let $X = \lrg{1, \ldots, N}^\bbZ$. We get it to be an ultrametric space with $d(x, y) = 2^{-a(x, y)}$ where $a(x, y) = \min \lrg{\abs i \text{ s.t. } x_i \neq y_i}$.
    
    The shift operator $\sigma: X \rar X$ defined by $(\sigma x)_i = x_{i + 1}$ is $\cC^0$ and it's an homeo.

    Now let $\cA$ the $\sigma$-algebra generated by cilinders, where a cilinder is, fixed $k \in \bbN, j_1, \ldots, j_k \in \lrg{1, N}$ the set $\lrg{x \in X \mid x_{i_1} = j_1, \ldots, x_{i_k} = j_k}$.
    And, fixed $(p_1, \ldots, p_n) \in \Delta^N$, $\mu$ is the product measure $\mu(C^{i_1, \ldots, i_k}_{j_1, \ldots, j_k}) = p_{j_1} \cdot \ldots \cdot p_{j_k}$.
    Then $\mu(\sigma^{-1}(A)) = \mu(A) \quad \forall A \in \cA$ because this is true for cilinders.
    
    We then get that $h_{KS}(\sigma, \mu) = h_{KS}(\sigma, p_1, \ldots, p_n) = - \sum_{i = 1}^N p_i \log p_i$.

    *Ornstein theorem*: If two bernoulli schemes have the same entropy, they are isomorphic. [Without proof].
  - (*Topological Markov chains*) A generalization of Bernoulli schemes.
    Let $\Gamma$ be an oriented graph with $N$ nodes (i.e. a subset of $\lrg{1, \ldots, N}^2$ where $(i, j) \in \Gamma$ iff there is an arc going from node $i$ to node $j$).
    
    Define its adiacency matrix $A_\Gamma$ as $a_{ij} = \lrq{(i, j) \in \Gamma}$ (Iverson parenthesis notation).

    The associated space is $\Sigma_\Gamma = \lrg{x \in \lrg{1, \ldots, N}^\bbZ \mid \forall i (x_i, x_{i+1}) \in \Gamma}$, that is the possible vertex walks.
    The map is the shift on $\Sigma_\Gamma$ defined by $(\sigma x)_i = x_{i+1}$ with the distance $d(x, y) = 2^{-l(x, y)}$ where $l(x, y) = \inf\lrg{\abs i \mid x_i \neq y_i}$.
  
    /Possible properties of square matrices $A_{ij}$/:
    * *Nonnegative* if $a_{ij} \ge 0 \quad \forall i, j$
    * *Irreducible* If nonnegative and $\forall i, j : \exists n$ s.t. $(A^n)_{ij} > 0$ (i.e. there is a path from each vertex to each other)
    * *Aperiodic/transitive/primitive* if there $\exists n$ s.t. $\forall i, j$ it holds $(A^n)_{ij} > 0$.

    Moreover, $A_\Gamma$ transitive $\implies \Sigma_\Gamma$ topologically transitive
  - (*Random walk on $\bbZ$*) Let $\Sigma = \lrg{0, 1}^\bbN$ be a Bernoulli scheme and let $\phi: \Sigma \rar \bbZ$ be given by $x \mapsto (-1)^{x_0}$ where $x_0$ is the first coordinate of $x$.
    Taking the skew-product we get $T_\phi: \Sigma \times \bbZ \rar \Sigma \times \bbZ$ defined as $T_\phi(x, k) = (\sigma(x), k + \phi(x))$ and such a map is an extension of the Bernoulli shift.
  - (*IFS - Iterated Function Systems*) It is a topological dynsys on $(\cH(X), h)$ given by $\cS = \lrg{S_1, \ldots, S_m}$ contractions with Lipschitz constants $c_i \in [0, 1)$.
    Let $c = \max_i c_i$ and define the dynsys by $f(A) = \cup_{i=1}^m S_i(A)$.
    
    Such a map is a contraction on the Haussdorf space since $h(f(A), f(B)) \le c h(A, B)$ and by the contraction theorem, each $\cS$ has a unique attractor that we denote with $A(\cS) \in \cH(X)$.
    Moreover by the same theorem, $\forall B \in \cH(X)$ we have $h(\cS^n(B), A(\cS)) \le c^n h(B, A(\cS))$.

    Many fractals are IFS, such as the Cantor Set, the Sierpinski Triangle.

    *To plot the IFS attractor* one can begin with a single point and iterate such system.
    Suppose the system has $\card \cS = 3$ and $c = \frac12$, as it is for the Sierpinski Triangle.
    To have a decent resolution we need $n = 10$ steps, but we should then calculate $3^n$ points, that is proibitively large.
  - (*Probabilistic IFS as skew-products over Bernoulli schemes*) We can avoid the above problem in this way.

    Let as before $\cS = \lrg{S_1, \ldots, S_m}$ be contractions and give them some probabilities $(p_1, \ldots, p_m) \in \Delta^{m-1}$ (i.e. $p_i \in (0, 1)$ and $\sum_i p_i = 1$).
    Let $\Sigma_m = \lrg{1, \ldots, m}^\bbN$ and $\mu$ be the bernoulli measure on $\Sigma_m$ corresponding to $p_i$.

    Then we can define the skew product map $\hat f: \Sigma_m \times \cH(X) \rar \Sigma_m \times \cH(X)$ by $\hat f(\xi, A) = (\sigma(\xi), S_{\xi_0}(A))$.
    We have then $\hat f^n(\xi, A) = (\sigma^n(\xi), S_{\xi_{n-1}} \ldots S_{\xi_0}(A))$ and then there $\exists \lim_{n \rar \infty} \hat f^n(\xi, x_0)$ independent of $x_0$.
  - (*Baker map*) Defined on the unit square by $B(x, y) = (2x (\mod 1), z)$ where $z = \partdef{\frac y2 & x \le \frac12 \\ \frac y2 + \frac12 & x > \frac12}$.
    It is an ergodic, mixing map and can be seen as a factor of the bernoulli scheme $\Sigma_2^\bbZ$ by the projection $\pi((\xi_i)_{i \in \bbZ}) = (\sum_{i = 0}^\infty \xi_i 2^{-i}, \sum_{i = -1}^{- \infty} \xi_i 2^i)$.
* Spiegazioni
  - (*Measurable dynamics: obstructions to measure preserving*)
    1. Lack of compactness (e.g. $X = \bbR, f(x) = x + 1$)
    2. Discontinuity (e.g. $X = [0, 1]$, $f(x) = 0 \text{ if } x = 1$ and $f(x) = x \text{ if } x \neq 1$, the fixed point is not there)
  - (*Measurable dynamics: probabilistic pov*) $(X, \cA, mu, f)$:
    - $X$ is the "samples space"
    - $\cA$ is a "collection of events"
    - $\mu$ is "the probability" ($\mu(A) = \bbP(x \in A)$)
    - Observables in dynamics $\leftrightarrow$ "Random variables"
    - $\phi_n = \phi \circ f^n$ is the analogue of a "stochastic process"
  - (*Pseudo-Random Generators*) We want to generate numbers according to the Cauchy distribution $\de\mu(x) = \frac{\de}{\pi (1 + x^2)}$, that we know is associated (is an invariant measure to the ergodic dynsys) $f(x) = \frac12 \lrt{x - \frac1x}$ on $\bbR$.
    By conjugacy ($z = \frac{x - i}{x + i}$) we get the doubling map on the circle: $T(\theta) = 2 \theta (\mod 1)$.

    Not, to get an almost-Gaussian generator, we can do a change of variables $h(x) = \log \frac{x}{1 - x}$ and obtain something similar to a Gaussian.
  - (*Relations TopDyn - ErgTheory*)
    | Topological Dynamics     | Ergodic Theory           |
    |--------------------------+--------------------------|
    | Topological Transitivity | Ergodicity               |
    | Minimality               | Unique Ergodicity        |
    | Topological Entropy      | Kolmogorov-Sinai entropy |
* Fatterelli e Teoremi
  - (*Multipliers*) For a fix point $x_0 \in X$ his multiplier is defined as the diffeomorphism derivative at the point $f'(x_0)$.
    If the orbit of $x_0$ is periodic of period $p$, then the multiplier is the product $\prod_{i=0}^{p-1} f'(x_i)$.
  - (*Top conj $\implies$ same multipliers*) If $f, g, h \in \cC^1$ and we have a fixed point $x_0 \in X$ (i.e. $gx_0 = x_0$, so also $f(h x_0) = h x_0$) then we have $f = h \circ g \circ h^{-1}$ and, denoted by $\bar{x_0} = h(x_0)$ we have that $f'(\bar{x_0}) = g'(\bar{x_0}) = \lambda$ i.e. the point multiplier is the same.
  - (*Theorem*) If $f$ is Devaney-chaotic on $X$ and $X$ has no isolated points then $f$ has SDOIC.
  - (*Krylov-Bogolyubov*) If $X$ is a complete metric space and $f \in \cC^0(X)$, then there $\exists \mu$ an $f$-invariant probability measure defined on borelians
    
    /Examples/ of invariant measure for irrational rotatons on the torus, the multiplying map.

    * Let now be $\cM(X)$ the space of probability measures on $X$ endowed with the weak${}^*$ topology, i.e. $\mu_n \rar \mu$ iff $\forall \phi \in \cC(X, \bbR)$ we have $\int_X \phi \de \mu_n \rar \int_X \phi \de \mu$. Then $\cM(X)$ is compact.
    * *Riesz representation theorem*: Let $j: \cC(X, \bbR) \rar \bbR$ a positive linear continuous functional with $j(\bb1) = 1$, then $\exists \mu \in \cM(X)$ s.t. $j(\phi) = \int_X \phi \de \mu$.
    * *Proof*: Given $f$, we define an action on $\cM(X)$ given by $(f_* \mu)(A) = \mu(f^{-1}(A))$.
      Pick up an initial measure $\mu_0 \in \cM(X)$ and define $\mu_m = \frac{1}{m} \sum_{j = 0}^{m - 1} f_*^j \mu_0$.
      By compactness there is a converging subsequence to an accumulation point $\nu \in \cM(X)$, that is invariant under $f_*$ and we have
      $$\int (\phi - \phi \circ f) \de \mu_n = \frac{1}{m} \abs{\int \sum_{j = 0}^{m - 1} (\phi \circ f^j - \phi \circ f^{j+1}) \de \mu} = \frac{1}{m} \lrt{\abs{\int \phi \de\mu} + \abs{\int \phi \circ f^{n+1} \de\mu}} \le \frac{2 \cdot \max_X \phi}{m} \rar_{m \rar \infty} 0$$
  - (*Poincaré recurrence theorem*) $\mu(A_\text{rec}) = \mu(A)$.
  - (*Unique erogidicity is equivalent to uniform convergence of Birkoff averages*) Let $X$ be a compact metric space, $\cA = \Bor(X)$, $f \in \cC^0$ and let us assume that $\cM_f(X) = \lrg\mu$. Then
    1. $\mu$ is ergodic
    2. $\forall \phi \in \cC(X, \bbR)$ the Birkoff averages converges uniformly to $\bbE$, i.e. $\frac1n \sum_{j = 0}^{n - 1} \phi \circ f^j \stackrel{\rar}{\rar} \int \phi \de\mu$.

    Also $(2) \implies $ unique ergodicity.
  
    /Lemmas/:
    1. $\mu \in \cM_f(X)$ is ergodic $\sse$ it is an extremal point of $\cM_f(X)$.
  - (*f-invariance, full support and ergodic => top transitivity*) If $\mu$ is $f$-invariant and has full support, $\mu$ ergodic $\implies$ that $X$ is top.transitive and moreover $\mu(\lrg{x \in X \mid \bar{\Orb_f(x)} = X}) = 1$.

    The converse is false: the counterexample is a time reparametrization of irrational linear flow $\phi$ on $\bbT^2$ which is top. transitive but the invariant probability measure is $M_{\phi_t} = \lrg{\delta_p}$.
    It is enough to have $\frac{\de t}{\de \tau} = \phi(x)$, i.e. slowing down the flux to let it have a fixpoint.

    But: *theorem*: If $f$ is uniquely ergodic and $\cM_f = \lrg\mu$ then $f$ is minimal iff $\mu$ has full support.
  - (*Gottschalk-Hedlund*) If $f$ is minimal and $\exists x_0 \in X$, $\exists C > 0$ s.t. $\forall n$ we have $\abs{\sum_{j = 0}^{n - 1} \phi \circ f^j(x_0)} \le C$ then $\exists \psi$ s.t. $\phi = \psi \circ f - \psi$.
  - (*Entropy variational principle*) Let $(X, d, f)$ be a top. dynsys and $\cP_f(X) = \cM_f(X) = \lrg{\mu \text{ prob. meas. on } Bor(X) \text{ that are invariant under } f}$.
    Then $h_{TOP}(f) = \sup_{\mu \in \cM_f(X)} h_\mu(f)$.
  - (*Perron-Frobenius*) Let $A$ be a nonnegative matrix. Then:
    1. If some column is not entirely zero, there $\exists \lambda > 0$ eigenvalue with an eigenvector $w \ge 0$.
    2. If $\exists \lambda, w$ s.t. $Aw = \lambda w$ with $\lambda > 0, w > 0$ then [...].
       Hence $\lambda$ is unique and any other eigenvalue satisfied $\abs\mu < \lambda$.
    3. If $A$ is irreducible, then if $Aw = \lambda w$ with $w \ge 0$, $\lambda > 0$, then $w > 0$.
    
    So, if $A$ is irreducible, there $\exists \lambda_A > 0$ eigenvalue s.t.
    1. $\forall \mu$ eigenvalue $\abs\mu < \lambda_A$
    2. The right eigenvector $w > 0$ corresponding to $\lambda_A$ is unique
    3. Any eigenvector $v \ge 0$ is a multiple of $w$
    4. If $A$ is aperiodic $\implies$ $\abs\mu < \lambda_A \quad \forall \mu \neq \lambda_A$

    If this happens, $(\lambda_A, w)$ are called Perron-Frobenius eigenvalue/eigenvector.
  - (*Multiplicative ergodic theorem 1968*)
    *Idea*: We have a disc dynsys $f \in \cC^1(\bbR^n)$ and let $x_0, x_1, \ldots$ be an orbit.
    We would like to calculate $J(x_n)J(x_{n-1})\cdot \ldots \cdot J(x_0)$ and see how it goes to $\infty$.
    We have ergodicity "$\sse$" it does not depend on $x_0$.

    *Statement*: Let $(X, \cA, \mu)$ be a probability space with $T: X \rar X$ measure preserving.
    Let $A: X \rar \cM(\bbR, k \times k)$ be measurable and such that $x \mapsto \log^+ \norm{A(x)} \in \cL^1(X, \mu)$.

    Then there $\exists B \in \cA$ s.t. $\mu(B) = 1$, $T(B) \subseteq B$ and:
    1. $\exists s: B \rar \bbN$ measurable s.t. $s \circ T = s$.
    2. If $x \in B$ then $\exists -\infty \le \lambda^1(x) < \lambda^2(x) < \ldots < \lambda^{s(x)}(x)$ 
       and linear subspaces $\lrg{0} = V^0(x) \subseteq V^1(x) \subseteq \ldots \subseteq V^{s(x)}(x) = \bbR^k$
       such that if $1 \le i \le s(x)$ then $\forall v \in V^i(x) \setminus V^{i-1}(x)$ we have
       $$\lim{n \rar \infty} \frac1n \log \norm{A(T^{n-1}(x)) \cdot \ldots \cdot A(x) \cdot v} = \lambda^{(i)}x$$

       Moreover, if $T$ is ergodic, such limit does not depend on the chosen point $x \in B$.
    3. $\lambda^i$ is defined and measurable on $\lrg{x \in B \mid s(x) \ge i}$ and $\lambda^i(T(x)) = \lambda^i(x)$ and on such set we have $A(x) V^i(x) \subseteq V^i(T(x))$.
  - (*Smooth ergodic theory*)
    *Theorem statement for invertible A, T*: Let $T$ be invertible and measure preserving wrt $(X, \cA, \mu)$, $A: X \rar GL(\bbR, k\times k)$ measurable and s.t. $x \mapsto \log^+ \norm{A(x)} \in \cL^1(X, \mu)$ and $x \mapsto \log^+ \norm{A^{-1}(x)} \in \cL^1(X, \mu)$.

    Then there $\exists C \in \cA$ with $\mu(C) = 1$ totally invariant $T(C) = C$ s.t. $\forall x \in C$ $\exists \bbR^k = W^1(x) \oplus \ldots \oplus W^{s(k)}(x)$, s.t. $\forall v \in W^i(x) \setminus 0$ we have
    $$\lim_{n \rar \infty} \frac1n \log\norm{A(T^{n-1}(x)) \cdot \ldots \cdot A(x) \cdot v} = \lambda^i x$$
    $$\lim_{n \rar \infty} \frac1n \log\norm{\lrq{A(T^{-1}(x)) \cdot \ldots cdot A(T^{-n}(x))}^{-1} \cdot v} = \lambda^i x$$
* Divagazioni e Conti
  | Topic                                                | Date        | Notes                                                                                  |
  |------------------------------------------------------+-------------+----------------------------------------------------------------------------------------|
  | Lorenz Attractor                                     | 14/11       | Lorenz's article and the counterexample                                                |
  | Invariant measure for $P\cC^1$, Farey map, Gauss map | 14/11       |                                                                                        |
  | Almost gaussian generators and Gauss Map             | 23/11       |                                                                                        |
  | Teoria di Fourier                                    | 21/11-23/11 |                                                                                        |
  | Small perturbations of hamiltonian systems           | 28/11       |                                                                                        |
  | Poincaré nonexistance theorem                        | 30/11       | Precise statement, proof in ___                                                        |
  | Furstenberg's Example                                | 05/12       | Smooth minimal diffeo of the torus which preserves the Haar measure but is not ergodic |
  | Transfer and expanding maps of intervals             | 12/12       |                                                                                        |
  | Interval Exchange transformations                    | 19/12       |                                                                                        |
  | Rauzy-Veech algorithm                                | 14/12       | To get the dual of an IET                                                              |
  | Spectral theory of dynamical system                  | 11/01       |                                                                                        |
  | Perron-Frobenius and Markov Chains                   | 16/01       |                                                                                        |
  | Asyntotic behaviour of powers                        | 18/01       |                                                                                        |
  | Information Theory and Shannon article               | 25/01-30/01 |                                                                                        |
** Esercizi da svolgere
   1. Sequenza della prima cifra di $2^k$: $1, 2, 4, 8, 1, 3, 6, ...$.
      È più frequente che esca $7$ o $8$?
* Libri suggeriti
  - Walters, An introduction to ergodic theory (GTM, Springer)
    * pages 233-234 (Multiplicative Ergodic Theorem)
  - Cornfeld-Fomin-Sinai, Ergodic theory
  - Knuth, The Art of Computer Programming (Chapters on pseudorandom number generators)
  - Widgerson of IAS Princeton, Talks on Pseudorandomness and randomness
  - Appendice di Diana & Oliveira, Foundations of Ergodic Theory
  - Chapter 9 of Falconer's "Fractal Geometry"
* Lezioni mancanti
  - 07/12/2017
  - 12/12/2017 Recuperare appunti propri
