#+TITLE: Fatti di Teoria dei Giochi
#+AUTHOR: Dario Balboni
#+LATEX_HEADER: \input{latex-abbreviations}
#+LATEX_HEADER: \usepackage[top=20mm,bottom=20mm,right=16mm,left=16mm]{geometry}

* Definizioni
  - Gioco strategico non cooperativo :: è una tupla $(N, S, \mu)$ dove
    * $N = \lrg{1, \ldots, n}$ è un insieme di giocatori
    * $S_i$ è un insieme di strategie per il giocatore $i$
    * $\mu_i: S \rar \bbR$ è detta funzione di utilità o payoff del giocatore $i$

    Ogni giocatore mira a massimizzare la sua funzione di utilità $\mu_i$ sul proprio insieme di strategie $S_i$.
  - Insieme delle risposte ottime :: è definito come $r_i(x_{-i}) = \argmax_{y \in S_i} \mu_i(y, x_{-i})$ che è dunque una funzione $S_{-i} \rar \cP(S_i)$.
  - Punto di equilibrio :: $x \in S$ è punto di equilibrio se $x_i \in r_i(x_{-i})$ per ogni $i$.
  - Minimo guadagno :: Definiamo $w_i(x_i) = \inf_{x_{-i} \in S_{-i}} \mu_i(x_i, x_{-i})$ che indica quanto guadagna al minimo il giocatore se sceglie la strategie $x_i$.
  - Valore di sicurezza :: $v_i = \sup_{x_i \in S_i} w_i(x_i)$, dove il giocatore cerca di usare la strategia che gli garantisce il maggior guadagno minimo.
  - Strategia di sicurezza :: Se $\bar{x_i} \in \argmax_{x_i \in S_i} w_i(x_i)$.
  - Giochi sequenziali :: I giocatori decidono le loro strategie in sequenza, possono essere rappresentati come grafo delle mosse quando sono ad informazione perfetta e completa.
  - Giochi strettamente competitivi :: Un gioco a due giocatori è strettamente competitivo se per ogni coppia di profili di strategie $(x_1, x_2), (x_1', x_2') \in S$:
       $$\mu_1(x_1, x_2) > \mu_1(x_1', x_2') \sse \mu_2(x_1, x_2) < \mu_2(x_1', x_2')$$
  - Giochi a somma nulla :: Se vale che $\mu_1(x_1, x_2) = - \mu_2(x_1, x_2)$ per ogni $(x_1, x_2) \in S$.
       In questo caso il gioco è sempre strettamente competitivo e si definisce $\mu = \mu_1 = - \mu_2$.

       Calcolando due strategie di sicurezza per i giocatori si ha $v_1 \le v_2$ (dove $v_2 = \inf_{x_2} \sup_{x_1} \mu(x_1, x_2)$).
       Se $v_1 = v_2$ allora $v := v_1 = v_2$ si dice valore del gioco.
  - Giochi matriciali :: Se abbiamo un gioco a due giocatori con $S_1 = \lrg{1, \ldots, n_1}$ ed $S_2 = \lrg{1, \ldots, n_2}$ finiti, chiamiamo $A = \lrq{\mu(x_i, x_j)}_{i, j}$ la matrice del gioco.

       Un gioco matriciale si dice simmetrico se $A$ è quadrata e antisimmetrica.
       In tal caso ha un equilibrio di nash se e solo se una riga ha valori tutti positivi o nulli (ed il valore del gioco sarà nullo, nell'intersezione di tale riga con la diagonale).
  - Strategie Miste :: Sono una distribuzione di probabilità sulle strategie pure di un giocatore, utilizzate per rendere lo spazio delle strategie un convesso compatto.
  - Strategia dominante :: Una strategia $\bar{s_i} \in S_i$ si dice dominante se $\mu_i(\bar{s_i}, s_{-i}) \ge \mu_i(s_i, s_{-i})$ per ogni $s_i, s_{-i}$.
       Si dice strettamente dominante se la disuguaglianza vale con il maggiore stretto.
  - Strategia dominata :: $\bar{s_i} \in S_i$ si dice strettamente dominata se $\exists s_i^* \in S_i$ tale che $\mu_i(\bar{s_i}, s_{-i}) < \mu_i(s_i^*, s_{-i})$ per ogni $s_{-i}$.
       Si dice debolmente dominata se invece $\exists s_i^* \in S_i$ tale che $\mu_i(\bar{s_i}, s_{-i}) \le \mu_i(s_i^*, s_{-i})$ per ogni $s_{-i}$ ed esiste invece un $s_{-i}^*$ tale che $\mu_i(\bar{s_i}, s_{-i}^*) < \mu_i(s_i^*, s_{-i}^*)$.
  - Mai Miglior Risposta :: Una strategia $s_i \in S_i$ è una MMR se per ogni $s_{-i}$ si ha $s_i \notin r_i(s_{-i})$.
       Notiamo che le strategie strettamente dominate sono in particolare MMR.
  - Gioco Potenziale :: Dato un gioco, una funzione $P: S \rar \bbR$ si dice potenziale esatto se vale
       $$\mu_i(\bar{s_i}, s_{-i}) - \mu_i(\hat{s_i}, s_{-i}) = P(\bar{s_i}, s_{-i}) - P(\hat{s_i}, s_{-i}) \quad \forall i \quad \forall \hat{s_i}, \bar{s_i} \in S_i \quad \forall s_{-i} \in S_{-i}$$

       Dato un gioco $G$ con $S_i \subseteq \bbR^n$ convessi e chiusi, e con funzioni di utilità $\mu_i \in \cC^1(S)$, allora presa una funzione $P \in \cC^1(S)$ questa è un potenziale esatto per $G$ se e solo se $\nabla_i \mu_i \equiv \nabla_i P \quad \forall i \in N$.

       I massimi del potenziale sono equilibri del gioco, mentre non è vero il viceversa.
  - Potenziale Ordinale :: Una funzione $P: S \rar \bbR$ per un gioco $G$ è un poteziale ordinale se vale
       $$\mu_i(\bar{s_i}, s_{-i}) - \mu_i(\hat{s_i}, s_{-i}) > 0 \sse P(\bar{s_i}, s_{-i}) - P(\hat{s_i}, s_{-i}) > 0$$
  - Gioco Leader-Multifollower :: Un gioco Leader-Multifollower è composto da:
       * Un leader che decide la prima mossa $s_1 \in S_1$
       * $n - 1$ follower che partecipano contemporaneamente ad un gioco parametrico in $s_1$
	 $$G(s_1) = \lrg{\lrg{2, \ldots, n}, \lrg{S_i}_{i > 1}, \lrg{\mu_i(s_1, \cdot)}_{i > 1}}$$
       * Indichiamo con $EN(s_1)$ gli equilibri del gioco $G(s_1)$.
  - Giochi Cooperativi :: Un gioco cooperativo è dato da una funzione che associa ad ogni sottoinsieme di $N$ una utilità $v: \cP(N) \rar \bbR$ dove per convenzione $v(\emptyset) = 0$.
       Si suppone che le utilità delle coalizioni siano maggiori della somma delle utilità dei singoli, altrimenti non ci sarebbe guadagno a cooperare.

       Un gioco cooperativo inoltre viene detto *semplice* se la funzione utilità ha valori in $\lrg{0, 1}$.

       Notiamo che si può trasformare un gioco non cooperativo in uno cooperativo (non equivalente) con gli stessi giocatori, dove $v(T)$ è il guadagno minimo che avrebbero i giocatori in $T$ a collaborare contro i restanti $N \setminus T$.
  - Giochi cooperativi 
* Giochi non cooperativi
** Fatti di base
   - Equilibri di un gioco a somma nulla :: Gli equilibri di un gioco a somma nulla sono coppie di strategie di minimax.
	Inotre, se il gioco ha un valore, allora vale il viceversa.
   - Teorema di Minimax :: Dato un gioco a due giocatori a somma nulla, supponiamo che $S_1, S_2$ siano convessi e compatti, $\mu: S \rar \bbR$ continua e concava nella prima variabile e convessa nella seconda.
	Allora vale che $\max_{x_1} \min_{x_2} \mu(x_1, x_2) = \min_{x_2} \max_{x_1} \mu(x_1, x_2)$.
   - Equilibri di un gioco finito a somma nulla :: Ogni estensione alle strategie miste ammette un equilibrio per il teorema del minimax.
   - Proprietà di estensione alle strategie miste :: Se una strategia era equilibrio nel gioco finito, allora lo è anche nel gioco esteso alle strategie miste.
	Inoltre, una strategia mista è un equilibrio se e solo se per ogni giocatore $i$ e per ogni strategia pura $s_i \in S_i$ .... Vedere Lemma 6 del Barbarino.
   - Nikaido-Isoda :: Se abbiamo $S_i$ convesso compatto, $\mu_i$ SCS nella prima variabile e SCI nella seconda (vettoriale) e $r_i(s_{-i})$ convesso per ogni $s_{-i} \in S_{-i}$ allora il gioco ammette un equilibrio di Nash.
   - Lemma di restrizione :: Dato $G' = (N, \lrg{T_i}_i, \mu)$ la restrizione di $G = (N, \lrg{S_i}_i, \mu)$ ottenuta eliminando una sola volta le strategie strettamente dominate. Allora vale che:
     * Se $s^* \in S$ è un equilibrio per $G$, allora $s^* \in T = \prod_i T_i$ ed è un equilibrio per $G'$
     * Se $G$ è finito ed $s^* \in T$ è un equilibrio per $G'$, allora $s^*$ è pure un equilibrio per $G$

     Al posto di $G$ finito si può richiedere gli $S_i$ compatti e le $\mu_i$ SCS, ed il secondo punto non cambia.
     Ancora, se eliminiamo le strategie /debolmente dominate/ invece delle strettamente dominate, il secondo punto vale ancora, mentre il primo no.

     Quindi:
     * Eliminando strettamente dominate $\rar$ Il gioco finale contiene gli stessi equilibri del gioco iniziale
     * Eliminando debolmente dominate $\rar$ Possiamo perdere equilibri, ma quelli del gioco finale sono anche equilibri del gioco iniziale

     Eliminando le MMR entrambi i punti si preservano.
** Algoritmi risolutivi
*** Eliminazione Dominate
    Ovviamente un giocatore non giocherà mai una strategia dominata, quindi possiamo provare ad eliminarle:
    1. Poniamo $S_i^0 = S_i$ per ogni giocatore $i$ e poniamo $k = 0$
    2. Definiamo il $k$-esimo gioco $G^k = (N, \lrg{S_i^k}_{i \in \bbN}, \mu)$
    3. Aggiorniamo gli $S_i^k$ eliminando le strategie dominate ad ogni passo:
       $$S_i^{k+1} = \lrg{x \in S_i^k \mid x \text{ non è dominata in } S_i^k}$$
    4. Dato $S^{k+1} = \prod_{i \in \bbn} S_i^{k+1}$, se $\abs{S^{k+1}} \le 1$ allora terminiamo
    5. $k = k+1$ e torniamo al passo (2).

    Non abbiamo specificato se volgiamo togliere le strategie debolmente o strettamente dominate, e vorremmo sapere alla fine se ci rimangono equilibri di Nash e quanti ce ne restano.
    Possiamo notare che se gli $S_i$ sono non vuoti allora ad ogni $k$ anche gli $S_i^k$ non possono essere vuoti, poiché due strategie non possono essere dominate l'una dall'altra.
    Inoltre si conclude per il lemma di restrizione.
*** Migliori Risposte Successive
    1. Iniziamo da un profilo $s^0 \in S$ casuale e poniamo $k = 0$
    2. Se $s^k \in r(s^k)$ ci fermiamo (altrimenti potremmo ciclare tra equilibri)
    3. Scegliamo un $s^{k+1} \in r(s^k)$
    4. Se $s^{k+1} = s^k$ ci fermiamo
    5. Poniamo $k = k + 1$ e torniamo al passo (2)

    Se $r$ è una contrazione, allora questo algoritmo converge.
*** Migliori Risposte Successive Asincrono
    1. Iniziamo da un profilo $s^0 \in S$ casuale e poniamo $k = 0$
    2. Ordinatamente rispetto ad $i = 1, \ldots, n$ scegliamo $s_i^{k+1} \in r_i(s_1^{k+1}, \ldots, s_{i-1}^{k+1}, s_{i+1}^k, \ldots, s_n^k)$.
       Se $s_i^k \in r_i(s_1^{k+1}, \ldots, s_{i-1}^{k+1}, s_{i+1}^k, \ldots, s_n^k)$, allora poniamo $s_i^{k+1} = s_i^k$ (per aumentare ad ogni ciclo la funzione utilità).
    3. Se $s^{k+1} = s^k$ ci possiamo fermare
    4. Poniamo $k = k + 1$ e torniamo al passo (2)$

    Se $G$ è un gioco finito con potenziale ordinale o esatto, allora l'algoritmo MRS asincrono individua un equilibrio in un numero finito di mosse.
** Esempi di giochi
   - Dilemma del prigioniero
   - Battaglia dei sessi
   - Caccia al cervo (esempio di gioco di coordinamento)
   - Falco e Colomba (esempio di chicken game)
   - Morra Cinese
* Giochi Concavi
** Definizioni
   - Contrazione :: È una funzione $f$ per cui vale $\norm{f(x) - f(y)} \le \rho \norm{x - y}$ con $\rho < 1$.
		    Sappiamo che $f$ ammette sempre un unico punto fisso se $f: X \rar X$ con $X$ compatto.
   - Stretta concavità :: Una funzione $f \in \cC^1$ si dice strettamente concava se e solo se
	$$(\nabla f(x) - \nabla f(y))^T (y - x) > 0 \quad \forall x \neq y \in \bbR^n$$
	
     * Dato $X \subseteq \bbR^n$ convesso ed $f$ strettamente concava si ha $\abs{\argmax\lrg{f(x) \mid x \in X}} \le 1$.
   - Forte concavità :: Una funzione $f: \bbR^n \rar \bbR$ si dice fortemente concava di modulo $\tau > 0$ se
	$$f(\lambda x + (1 - \lambda) y) \ge \lambda f(x) + (1 - \lambda) f(y) + \frac\tau2 \lambda (1 - \lambda) \norm{x - y}^2 \quad \forall \lambda \in \lrq{0, 1} \quad \forall x, y \in \bbR^n$$

     * Dato $X \subseteq \bbR^n$ convesso chiuso ed $f$ fortemente concava di modulo $\tau > 0$, allora $\abs{\argmax\lrg{f(x) \mid x \in X}} = 1$.
     * Una funzione $f \in \cC^1$ è fortemente concava di modulo $\tau$ se e solo se vale $\lrt{\nabla f(x) - \nabla f(y)}^T \lrt(y - x) \ge \tau \norm{x - y}^n \quad \forall x, y \in \bbR^n$.
     * Una funzione $f$ è fortemente concava di modulo $\tau$ se e solo se $f + \frac\tau2 \norm{\cdot}^2$ è concava.
     * Una funzione $g$ è fortemente concava di modulo $\tau$ se e solo se $g(y) \le g(x) + \nabla g(x)^T (y - x) - \frac\tau2 \norm{y - x}^2$.
   - Gioco Strettamente Concavo in Diagonale :: Un gioco $G$ con $\mu_i \in \cC^1$ si dice strettamente concavo in diagonale se
	$$\sum_{i=1}^n \lrt{\nabla_i \mu_i(s_i, s_{-i}) - \nabla_i \mu_i(s_i', s_{-i}')}^T (s_i' - s_i) > 0 \quad \forall s \neq s' \in S$$

	VERIFICARE: Viene sostenuto che questo implica che le $\mu_i$ siano concave nella prima variabile.
   - Jacobiana del gioco :: $J_F(s)_{ij} = \nabla_j \nabla_i^T \mu_i(s)$ dove $\nabla_i$ è il gradiente colonna rispetto alle coordinate di $S_i$.
   - Disuguaglianza variazionale :: Detto $F = (- \nabla_i \mu_i)_i$ il gradiente del gioco ci riferiremo al problema $F(x)^T (s - x) \ge 0 \quad \forall s \in S$ come disuguaglianza variazionale o (VI).
	
	Dato un gioco $G = (N, S, \mu)$ con $S_i \subseteq \bbR^{m_i}$ convessi e chiusi e $\mu_i \in \cC^1$ allora:
        - Se $s^*$ è un equilibrio, allora soddisfa (VI)
        - Se le $\mu_i(\cdot, s_{-i})$ sono concave per ogni $s_{-i} \in S_{-i}$ ed $s^*$ risolve (VI) allora $s^*$ è un equilibrio
	  
     Inoltre se $F$ è continua ed $S$ compatto, allora (VI) ammette almeno una soluzione per il teorema di punto fisso di Brouwer.
   - Equilibri come punti fissi :: Se gli $S_i$ sono convessi chiusi e $\mu_i \in \cC^1$ sono concave nella prima variabili allora
	$s^*$ è equilibrio se e solo se è punto fisso della mappa $\psi(s) = P_S(s - t F(s))$.

   - Disuguaglianza di Ky-Fan :: Definiamo la funzione aggregata di Nikaido-Isoda: $f: S \times S \rar \bbR$ come $f(s, v) = \sum_i \mu_i(s_i, s_{-i}) - \mu_i(v_i, s_{-i})$ che rappresenta la somma delle perdite se passo da $s$ a $v$.
	La disuguaglianza di Ky-Fan è $f(x, v) \ge 0 \quad \forall v \in S$.

	Sono equivalenti:
        - $\bar s$ è un equilibrio
        - $f(\bar s, v) \ge 0 \quad \forall v \in S$
        - $\bar s \in \argmin_{v \in S} f(\bar s, v)$
   - Gap o Funzione di Merito :: Viene detta $V(s) = \inf_{v \in S} f(s, v)$ che ci dice quanto al massimo possiamo andare a perdere cambiando strategia (e può anche valere $-\infty$).

        $\bar s$ è un equilibrio se e solo se $V(\bar s) = 0$. In questo caso $\bar s$ è un massimo di $V(s)$.
   - Soluzione alla disuguaglianza di Ky-Fan :: La disuguaglianza di Ky-Fan ammette almeno una soluzione se:
	- $S$ è compatto e convesso
	- $f$ è continua
        - $f(s, \cdot)$ è (quasi) convessa per ogni $s \in S$
** Algoritmi
*** Proiezione
    Lavoriamo sotto ipotesi di chiusura e convessità degli $S_i$ e concavità delle $\mu_i$ nella prima variabile.
    1. Fissiamo $t > 0$, $s^0 \in S$, $k = 0$
    2. Generiamo $s^{k+1} = P_S(s^k - tF(s^k))$
    3. Se $s^{k+1} = s^k$ ci fermiamo
    4. Poniamo $k = k + 1$ e torniamo a (2)

    Inoltre si hanno i risultati:

    - Teorema di convergenza :: Supponiamo che $F$ sia $L$-lipschitz su $S$ e fortemente monotona di modulo $\tau$ su $S$.
	 Se $t < \frac{2\tau}{L^2}$ allora gli $s^k$ generati dall'algoritmo di proiezione convergono all'unico equilibrio del gioco.

	 Inoltre il gradiente proiettato applicato ad una $F$ $\tau$-fortemente monotona e con $\nabla F$ Lipschitz di modulo $L < 2 / t$ converge ad un massimo globale di $F$.
*** Extragradiente
    1. Fissiamo $t > 0$, $s^0 \in S$, $k = 0$
    2. $\hat s^k = P_S (s^k - t F(s^k))$
    3. Se $\hat s^k = s^k$ fermiamo l'algoritmo
    4. $s^{k+1} = P_S(s^k - t F(\hat s^k))$
    5. Poniamo $k = k + 1$ e torniamo allo step (2)

    Il teorema di convergenza richiede che:
    - $S$ sia chiuso e convesso
    - (VI) ammetta una soluzione $\bar s \in S$
    - $F$ sia lipschitziana di modulo $L$ su $S$
    - $F$ sia monotona su $S$, ovvero valga $\forall s, s' \in S$ che $\lrt{F(s) - F(s')}^T (s - s') \ge 0$
    - $0 < t < 1 / L$
    Allora le $s^k$ generate dall'algoritmo dell'extragradiente convergono ad una delle soluzioni di (VI)
*** Extragradiente con Iperpiano
    1. Fissiamo $t > 0$, $s^0 \in S$, $k = 0$
    2. $\hat s^k = P_S(s^k - tF(s^k))$
    3. Se $\hat s^k = s^k$ fermiamo l'algoritmo
    4. $s^{k+1} = P_S(P_{H_k}(s^k))$
    5. Poniamo $k = k + 1$ e torniamo allo step (2)

    Nello step (4) è sottointesa la scelta di una successione $\theta^k$ per generare gli iperpiani dalla formula $H_k = \lrg{s \in \bbR^n \mid F(z^k)^T(s - z^k) = 0}$ dove $z^k = \theta^k \hat s^k + (1 - \theta^k) s^k$ con $\theta^k \in \lrt{0, 1}$.

    Le ipotesi di convergenza in questo caso sono:
    - $S$ sia chiuso e convesso
    - (VI) ammetta una soluzione in $S$
    - $F$ sia continua e monotona
    - $t > 0$
    In questo caso le $s^k$ generate dall'extragradiente con iperpiano convergono ad una soluzione di (VI)
*** Rilassamento
    1. Prendiamo $s^0 \in S$, $k = 0$ ed una sequenza $\lrg{t_k}_k \subseteq \lrq{0, 1}$
    2. $z^k = \argmin_{v \in S} f(s^k, v)4
    3. Se $z^k = s^k$ fermiamo l'algoritmo
    4. $s^{k+1} = (1 - t_k) s^k + t_k z^k$
    5. Poniamo $k = k + 1$ e torniamo allo step (2)

    Vale il seguente teorema per quanto riguarda le ipotesi di convergenza: se supponiamo che
    - $S$ è compatto e convesso
    - $f$ è continua
    - $f(s, \cdot)$ fortemente convessa di modulo $\alpha > 0$ per ogni $s \in S$
    - $f(\cdot, v)$ è concava per ogni $v \in S$
    - $t_k \rar 0$ converge a zero
    - $\sum_{i=1}^\infty t_k = \infty$ diverge
    allora esiste un punto di accumulazione della sequenza $s^k$ che risolve Ky-Fan.
*** Ascesa per V
    Nelle ipotesi in cui per ogni $s \in S$ esiste un unico punto di minimo di $\argmin_{v \in S} f(s, v)$, chiamato $z(s)$, allora sotto le ipotesi del teorema del rilassamento (aggiungendo che $f \in \cC^1$) si ottiene che $z(s) - s$ è sempre la direzione di crescita stretta per $V$ fino ad arrivare alla soluzione per la quale si ha $z(s) = s$.
    
    1. Prendiamo $s^0 \in S$, $k = 0$
    2. $z^k = \argmin_{v \in S} f(s^k, v)$
    3. Se $z^k = s^k$ fermiamo l'algoritmo
    4. $s^{k+1} = s^k + t_k (z^k - s_k)$
    5. Poniamo $k = k + 1$ e torniamo allo step (2)

    La differenza con l'algoritmo di rilassamento è la scelta di $t_k = \beta^p$ con $\beta \in \lrt{0, 1}$ e $p$ il più piccolo intero positivo che soddisfi
    $$V(s^k + \beta^p (z^k - s^k)) \ge V(s^k) + \frac\alpha2 \eta \beta^p \norm{z^k - s^k}^2$$

    Supponiamo che:
    - $S$ è compatto
    - $f \in \cC^1$
    - $f(s, \cdot)$ è fortemente convessa di modulo $\alpha > 0$ per ogni $s \in S$
    - $f(\cdot, v)$ è concava per ogni $v \in S$
    Allora *ogni* punto di accumulazione della successione $s^k$ generata dall'algoritmo di ascesa di $V$ risolve Ky-Fan.

    
* Casi di Duopolio
** Duopolio di Cournot
   - Il bene è Omogeneo, ovvero le due produzioni sono indistinguibili
   - La competizione viene fatta sulla quantità prodotta
   - Il prezzo è fissato per entrambi dal Mercato ed è uguale

   Sia $x_i \in \bbR^+$ la produzione dell'azienda $i$ e $c_i: \bbR_+ \rar \bbR_+$ la funzione che stabilisce il costo di produzione $c_i(x_i)$.
   La funzione di domanda inversa è $p: \bbR_+ \rar \bbR_+$ che indica il massimo prezzo per unità che consente di vendere *tutta* la produzione $z$, e quindi è il prezzo ideale a cui vendere.
   
   I profitti saranno:
   #+BEGIN_eqn
   $\mu_1(x_1, x_2) = x_1 p(x_1 + x_2) - c_1(x_1)$ \\
   $\mu_2(x_1, x_2) = x_2 p(x_1 + x_2) - c_2(x_2)$ \\
   #+END_eqn

   In questa situazione le aziende vogliono determinare la propria produzione $x_i$ senza sapere quella del rivale.
   Supponiamo che:
   - I costi di produzione siano lineari ed identici $c_i(x) = cx$
   - La funzione $p$ decresca linearmente con la produzione $p(z) = \max\lrg{0, T - \alpha z}$

   Allora l'equilibrio di Nash è per $x_1 = x_2 = \frac{T - c}3$ e quindi il ricavo di ciascuna è $\frac{(T - c)^2}9$.
   Se invece entrambe si fossero messe d'accordo potevano ottenere di meglio, producendo ciascuna $\frac{T - c}4$ e quindi ricavando $\frac{(T - c)^2}8$.

   Dal punto di vista del consumatore quindi il duopolio è conveniente.
   La differenza tra il profitto nel Monopolio ed il profitto nell'equilibrio si chiama /prezzo dell'anarchia/.
** Duopolio di Bertrand
   - Il bene *non* è omogeneo
   - Le quantità vendute sono determinate dal prezzo
   - La competizione viene fatta sul prezzo

   Supponiamo ancora il costo di produzione unitario costante $c$ ed uguale per le due aziende..
   Il prezzo sarà $p_i$ e la produzione $x_i$ dipende dai prezzi $x_i = q_i(p_1, p_2)$.
   Il guadagno sarà quindi
   #+BEGIN_eqn
   $\mu_i(p_1, p_2) = q_i(p_1, p_2) (p_i - c)$ \\
   #+END_eqn
   
   Nel caso di *beni omogenei* si suppone che $q_1(p_1, p_2)$ valga $Q - p_1$ se $p_1 < p_2$, $\frac{Q - p_1}2$ se $p_1 = p_2$ e $0$ altrimenti, dove $Q > c$.
   Facendo un'analisi come prima si ricava che il caso di equilibrio si ha per $p_1 = p_2 = c$ ma in questo caso nessuna delle due aziende guadagnerebbe.

   Nel caso di *beni non omogenei*, invece, le due funzioni $q_i$ sono differenti:
   #+BEGIN_eqn
   $q_1(p_1, p_2) = \max\lrg{0, Q - p_1 + qp_2}$ \\
   $q_2(p_1, p_2) = \max\lrg{0, Q + p_1 - qp_2}$ \\
   #+END_eqn
   con $Q > c$ e $q > 0$.
   Le funzioni di miglior risposta saranno:
   #+BEGIN_eqn
   $r_1(p_2) = \frac{Q + qp_2 + c}2$ \\
   $r_2(p_1) = \frac{Q + qp_1 + c}2$ \\
   #+END_eqn

   Se $q < 2$ si ottiene l'equilibrio per $p_1 = p_2 = \frac{Q + c}{2 - q}$.
   Se invece $q \ge 2$ le due rette non si incontrano, ovvero i prezzi possono essere aumentati a piacimento da entrambe le aziende, e non esiste uno stato di equilibrio.
** Duopolio di Stackelberg
   Riprendiamo il setup del duopolio di Cournot ma aggiungiamo l'ipotesi di *sequenzialità*, ovvero le due aziende non scelgono la strategia contemporaneamente, ma agiscono una dopo l'altra.
   La prima azienda sa che se sceglie la strategia $s_1$, la seconda sceglierà sicuramente $r_2(s_1)$ che è $r_2(s_1) = \max\lrg{0, \frac{T - c - s_1}2}$.

   La prima azienda pertanto punterà a massimizzare $\mu_1(s_1, r_2(s_1))$.
   Le strategie scelte saranno pertanto $\bar s_1 = \frac{T - c}2$ e $\bar s_2 = r_2(\bar s_1) = \frac{T - c}4$.
* Nash Bargaining
  Dato un gioco, mettiamo che i giocatori possano decidere se mettersi d'accordo o meno, e se non si mettono d'accordo ottengono un utilità $u^* \in \bbR^n$ fissata.
  Un *problema di negoziazione* quindi è dato dalla coppia $(\cU, u^*)$ dove $\cU \subseteq \bbR^n$ e $u^* \in \bbR^n$.
  Trasformiamo $\cU$ nel suo inviluppo convesso attraverso l'utilizzo di strategie miste.

  Si dicono *assiomi di Nash* le proprietà seguenti:
  - $\cU \subseteq \bbR^n$ convesso e compatto
  - $\exists u \in \cU$ tale che $u > u^*$ componente per componente
  Chiamiamo $\cB$ l'insieme delle coppie $(\cU, u^*)$ che rispettano gli assiomi di Nash.

  Sotto questi assiomi ha senso cercare di mettersi d'accordo perché c'è una strategie in cui tutti guadagnano rispetto ad $u^*$.
  Nash si è chiesto se esista una funzione $\psi: \cB \rar \bbR^n$ che indichi la migliore utilità per la coppia $(\cU, u^*) \in \cB$, che vogliamo rispetti le seguenti proprietà:
  - Ammissibilità: $\psi(\cU, u^*) \in \cU$
  - Razionalità: $\psi(\cU, u^*) \ge u^*$
  - Ottimalità: Se $u \in \cU$ e $u \ge \psi(\cU, u^*)$ allora $u = \psi(\cU, u^*)$
  - Se $\cU_1 \subseteq \cU$ è un sottoinsieme per cui $(\cU_1, u^*) \in \cB$ allora $\psi(\cU, u^*) \in \cU_1 \implies \psi(\cU, u^*) = \psi(\cU_1, u^*)$
  - Invarianza traslazionale: Siano $\alpha_i > 0$ e $\beta_i$ relai. Allora detti $\hat u_i^* = \alpha_i u_i^* + \beta_i$ e detto $\hat\cU = \lrg{(\alpha_i u_i + \beta_i)_i \mid u \in \cU}$ si ha che $\psi(\hat \cU, \hat u^*)_i = \alpha_i \psi(\cU, u^*)_i + \beta_i$.
  - Simmetria: se esistono due indici $i$, $j$ su cui $\cU$ è simmetrico e $u^*_i = u^*_j$ allora $\psi(\cU, u^*)_i = \psi(\cU, u^*)_j$.

  *Teorema*: Esiste un'unica funzinone di negoziazione $\psi$ che soddisfi le condizioni di sopra. In particolare $\psi(\cU, u^*)$ è l'unica soluzione di
  $$\max \lrg{\prod_{k = 1}^n (x_k - u_k^*) \mid x \in \cU, x \ge u^*}$$
  Prima si mostra che il massimo è unico (l'esistenza è gratis dal fatto che $\cU$ sia compatto) e poi si mostra che tale punto rispetta tutti gli assiomi.

* Giochi cooperativi
  - Superadditivo :: Se vale $\forall T_1 \cap T_2 = \emptyset \quad v(T_1) + v(T_2) \le v(T_1 \cup T_2)$
		     Tale definizione si espande alle unioni di un numero finito di $T_i$ disgiunti, pertanto l'utilità delle coalizioni è maggiore della somma delle utilità dei singoli.
  - Monotono :: Se vale $\forall T_1, T_2 \quad T_1 \subseteq T_2 \implies v(T_1) \le v(T_2)$
		Se la funzione $v$ è a valori non-negativi, allora un gioco superadditivo è monotono.
  - Giochi Strategicamente Equivalenti :: Due giochi cooperativi $(N, u)$ e $(N, v)$ vengono detti strategicamente equivalenti se esistono $a \in \bbR^+$ e $b \in \bbR^n$ per cui $\forall T \subseteq N$ si ha $u(T) = av(T) + b(T)$ dove $b(T) = \sum_{i \in T} b_i$.
       Questa è una relazione di equivalenza.

       La superadditività è invariante per equivalenza, mentre la monotonia no.
  - Normalizzazione di un gioco :: La relazione di equivalenza strategica ha tre classi:
       Un gioco $(N, v)$ si dice $0$ -- $\gamma$ Normalizzato se $v(i) = 0$ per ogni $i \in N$ e $v(N) = \gamma$, dove $\gamma = 0, 1, -1$.
       
       Dato un gioco $(N, v)$ esso è equivalente a:
    - Un gioco $0$ -- $1$ normalizzato se e solo se $\sum_{i \in N} v(i) < v(N)$
    - Un gioco $0$ -- $0$ normalizzato se e solo se $\sum_{i \in N} v(i) = v(N)$
    - Un gioco $0$ -- $-1$ normalizzato se e solo se $\sum_{i \in N} v(i) > v(N)$
  - Vettore Socialmente Razionale :: Data una partizione $\cB$ di $N$, $x \in \bbR^n$ si dice socialmente razionale se $x(S) = v(S) \quad \forall S \in \cB$

       La razionalità collettiva dice che tutto il guadagno della coalizione $S$ viene distribuito tra i membri.
  - Individualmente Razionale :: Se $\forall i \in N \quad x_i \ge v(i)$
       
       La razionalità individuale dice che ad ogni giocatore conviene coalizzarsi piuttosto che restare da solo.
  - Imputazione :: Relativa al gioco $G = (N, v)$ rispetto alla partizione $\cB$ è un vettore $x \in \bbR^n$ che rispetti la razionalità collettiva ed individuale.
  - Dominazione di imputazioni :: Un'imputazione $x$ domina $y$ tramite la coalizione $S \subseteq N$ se $\forall i \in S \quad x_i > y_i$ e se $x(S) \le v(S)$.

       Un'imputazione $x$ è *non dominata* se non esiste un'imputazione $y$ ed una coalizione $S \subseteq N$ tali che $y$ domini $x$ tramite $S$.
  - Nucleo :: Relativo al gioco $G = (N, v)$ è un sottoinsieme delle imputazioni:
	      $$C(N, v) = \lrg{x \in \bbR^n \mid \forall S \subseteq N \quad x(S) \ge v(S) \wedge x(N) = v(N)}$$

	      Il nucleo è sempre un poliedro limitato, quindi è convesso e compatto e contenuto nell'iperpiano $x(N) = v(N)$.
	      Inoltre se $(N, v)$ e $(N, av + b)$ sono equivalenti strategicamente, si ha che $a C(N, v) + b = C(N, av+b)$.
	      
	      Per un lemma, se $x \in C(N, v)$ è nel nucleo, allora $x$ è non dominata.
	      Inoltre, se $(N, v)$ è superadditivo, allora $C(N, v) = \lrg{x \in \bbR^n \mid x \text{ non è dominato}}$.
  - Bondareva-Shapley :: Il nucleo di $(N, v)$ è non vuoto se e solo se $\min_{x \in \bbR^n} \lrg{ x(N) \mid x(S) \ge v(S) \quad \forall S \subseteq N} \le v(N)$.
  - Gioco Bilanciato :: Dato un gioco $(N, v)$ sono equivalenti:
                   1. Il nucleo è non vuoto
		   2. Il valore di (P) è $\le v(N)$
                   3. Il valore di (D) è $\le v(N)$
		   4. $\sum_{S \subsetneq N} y_S v(s) \le v(N)$ per ogni $y$ nell'insieme bilanciato dei pesi.
                   In questo caso si dice che il gioco è bilanciato.
   - Gioco Ridotto di Mashler :: TODO
